development:
  adapter: mysql
  encoding: utf8
  database: pin_workspaces_development
  username: root
  password: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  encoding: utf8
  database: pin_workspaces_test
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: pin_workspaces_0531
  username: root
  password: m1ndp1n/^^
  pool: 5
  timeout: 5000